{"name": "test_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_login.TestLogin object at 0x0302BB50>\n\n    @pytest.mark.run(order=1)\n    def test_login(self):\n        print('aa')\n>       assert False\nE       assert False\n\nscripts\\test_login.py:6: AssertionError"}, "start": 1589189924395, "stop": 1589189924409, "uuid": "46a1e118-4974-4a0d-8fc0-cb6b0abf9684", "historyId": "161da9f82071fb37eae9201ae900aa4f", "testCaseId": "1d80d88536c622141c7393804df49bc9", "fullName": "scripts.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "lr-PC"}, {"name": "thread", "value": "8788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}